swagger: '2.0'
info:
  title: test-name-spec
  description: Sample API on API Gateway with a Google Cloud Functions backend
  version: 1.0.0
host: "vegvizer-exam.appspot.com"
schemes:
  - https
produces:
  - application/json
paths:
  /hello:
    get:
      summary: Greet a user
      operationId: hello
      # x-google-backend:
      #   address:
      responses:
        '200':
          description: A successful response
          schema:
            type: string